version: "3.7"

services:
  gateway:
    build:
      context: ../
      dockerfile: src/Gateway/Dockerfile
    container_name: gateway
    restart: unless-stopped
    ports:
      - 5000:80
    networks:
      - myspot

  saga:
    build:
      context: ../
      dockerfile: src/Saga/Dockerfile
    container_name: saga
    restart: unless-stopped
    ports:
      - 5010:80
    networks:
      - myspot

  availability-service:
    build:
      context: ../
      dockerfile: src/Services/Availability/Dockerfile
    container_name: availability-service
    restart: unless-stopped
    ports:
      - 5020:80 
    networks:
      - myspot

  mapping-service:
    build:
      context: ../
      dockerfile: src/Services/Mapping/Dockerfile
    container_name: mapping-service
    restart: unless-stopped
    ports:
      - 5030:80
    networks:
      - myspot

  parkingspots-service:
    build:
      context: ../
      dockerfile: src/Services/ParkingSpots/Dockerfile
    container_name: parkingspots-service
    restart: unless-stopped
    ports:
      - 5040:80
    networks:
      - myspot

  reservations-service:
    build:
      context: ../
      dockerfile: src/Services/Reservations/Dockerfile
    container_name: reservations-service
    restart: unless-stopped
    ports:
      - 5050:80
    networks:
      - myspot

  users-service:
    build:
      context: ../
      dockerfile: src/Services/Users/Dockerfile
    container_name: users-service
    restart: unless-stopped
    ports:
      - 5070:80
    networks:
      - myspot

  notifications-service:
    build:
      context: ../
      dockerfile: src/Services/Notifications/Dockerfile
    container_name: notifications-service
    restart: unless-stopped
    ports:
      - 5080:80
    networks:
      - myspot

networks:
  myspot:
    name: myspot-network
    external: true